---@class Palette
---@field bg string
---@field fg string
---@field selection string
---@field cursorline string
---@field comment string
---@field red string
---@field orange string
---@field yellow string
---@field green string
---@field purple string
---@field cyan string
---@field pink string
---@field bright_red string
---@field bright_green string
---@field bright_yellow string
---@field bright_blue string
---@field bright_magenta string
---@field bright_cyan string
---@field bright_white string
---@field menu string
---@field visual string
---@field gutter_fg string
---@field nontext string
---@field white string
---@field black string
---@field type_cyan string
---@field keyword_blue string
return {
   bg = "#191A1C",
   fg = "#F0F0F0",
   selection = "#08335E",
   cursorline = "#202424",
   comment = "#85C46C",
   red = "#FF5647",
   orange = "#FF9259",
   yellow = "#D9B72B",
   green = "#85C46C",
   purple = "#C191FF",
   cyan = "#39CC9B",
   pink = "#ED94C0",
   bright_red = "#FF8870",
   bright_green = "#ADEB96",
   bright_yellow = "#F5D86A",
   bright_blue = "#ADD3FF",
   bright_magenta = "#FFBFFE",
   bright_cyan = "#7DF0C0",
   bright_white = "#F0F0F0",
   menu = "#21222C",
   visual = "#232E46",
   gutter_fg = "#808080",
   nontext = "#404040",
   white = "#BDBDBD",
   black = "#191A1C",
   type_cyan = "#66C3CC",
   keyword_blue = "#6C95EB",
}
